# Info
baseURL = 'https://whereistherum.aao.fyi/'
languageCode = 'en'
title = 'Where Is The Rum?'

# Theme
theme = 'gitlab.com/aao-fyi/shock'

# Features
disableHugoGeneratorInject = false
disableKinds = ['taxonomy', 'term']
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.111.0'
  # IMFell
  [[module.imports]]
    path = 'gitlab.com/aao-fyi/resources/fonts'
  [[module.imports.mounts]]
    source = 'IMFell/'
    target = 'assets/fonts/imfell'

# Parameters
[params]
  description = "Four oh four, the rum is gone!"
  # PostCSS
  postCSS = true
  # Navbar
  navbarBrandLogo = true
  navbarBrandText = false
  navbarFixedTop = false
  # Manifest
  manifestJSON = false

# Menus
[menu]
  [[menu.footer]]
    identifier = 'source'
    name = 'Source'
    url = 'https://gitlab.com/aao-fyi/whereistherum'
    weight = 10
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    url = 'https://aao.fyi/privacy/'
    weight = 20

# Privacy
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

# Services
[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
